## -----------------------------------------------------------------------------
## GitLab CI configuration file
##
## @author     Lars Thoms <lars@thoms.io>
## @date       2023-05-08
## -----------------------------------------------------------------------------

---
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_BUILDKIT: 1
  CONTAINER_BUILD_IMAGE: "${CI_REGISTRY_IMAGE}:job-${CI_JOB_ID}"
  CONTAINER_RELEASE_IMAGE: "${CI_REGISTRY_IMAGE}:latest"

stages:
  - build

build-docker:
  stage: build
  image: docker:stable
  tags:
    - dl.min
  before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  script:
    - docker build --pull --build-arg BUILDKIT_INLINE_CACHE=1 --tag "${CONTAINER_BUILD_IMAGE}" .
    - docker push "${CONTAINER_BUILD_IMAGE}"
    - docker tag "${CONTAINER_BUILD_IMAGE}" "${CONTAINER_RELEASE_IMAGE}"
    - docker push "${CONTAINER_RELEASE_IMAGE}"
  only:
    - main
...
